server:
  port: ${SHOP_SERVICE_PORT:8083}

spring:
  application:
    name: hmdp-shop-service
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        register-enabled: ${NACOS_REGISTER_ENABLED:true}
        server-addr: ${NACOS_ADDR:42.193.185.40:8848}
      config:
        enabled: true
        server-addr: ${NACOS_ADDR:42.193.185.40:8848}
        file-extension: yaml
        shared-configs:
          - data-id: hmdp-common.yaml
            refresh: true
